### ISSUE TITLE
[feat] MetaDatum::Credits / "Rollen für Personen"

### ISSUE THREAD

**Issue by eins78** [Madek/madek#12]
**Judith Scheiber**: Responsible for the feature (requirements, testing, final approval)
 **Michal**: Development
 **ask Max**: Any questions to the project
Contents of project (structure, thoughts): **https://github.com/Madek/madek/projects/7**

**Specification written by Judith Scheiber - translated and shortened by Nadja:**
[20180502_Summary of Requirements.docx](https://github.com/Madek/madek/files/2223314/20180502_Summary.of.Requirements.docx)

> Personen sollen Rollen wie Regisseur, Ton, Schauspieler zugewiesen können.

### UI

- `MetaDatumInput`
- output/decorator

###  DB

- Mischung aus `Keywords`, `::People` und `::String`! Challenge: nicht zu viel und nicht zu wenig reusen!
  - mindestens aus admin/user sicht soll es möglichst gleich sein weil besser verständlich
- im idealfall auch noch mit `string`! (kommentar, spezifizierung)
  - z.b. bei rollen nach fixem schema (kino), aber irgendein spezialfall
  - bei Schauspieler der Charakter-Name
  - `$Person hatte bei $Film die Funktion $Rolle als $String`

```yaml
# example: http://www.imdb.com/title/tt4288182/fullcredits

# Atlanta (2016) (TV Series)
#   - Directed by: Donald Glover
#   - Writing Credits: Donald Glover
#   - Produced by: Donald Glover
#   - Cast: Donald Glover (Earnest 'Earn' Marks); Brian Tyree Henry (Alfred 'Paper Boi' Miles)

entries:
  - id: 1111

meta_keys:
  - id: 'credits:tv'
    label: 'TV-Serien Rollen'
    value_type: 'MetaDatum::Roles'

roles: # like keywords: unique terms per metakey, `#is_extensible?`
  - { id: 99991, term: 'Directed by' }
  - { id: 99992, term: 'Writing Credits' }
  - { id: 99993, term: 'Produced by ' }
  - { id: 99994, term: 'Cast' }

people:
  44441:
    name: Donald Glover # http://www.imdb.com/name/nm2255973
  44442:
    name: Brian Tyree Henry # http://www.imdb.com/name/nm3109964

meta_data:
  - meta_key_id: 'credits:tv'
    media_entry_id: 11111
    person_id: 44441
    role_id: 99991

  - meta_key_id: 'credits:tv'
    media_entry_id: 11111
    person_id: 44441
    role_id: 99992

  - meta_key_id: 'credits:tv'
    media_entry_id: 11111
    person_id: 44441
    role_id: 99993

  - meta_key_id: 'credits:tv'
    media_entry_id: 11111
    person_id: 44441
    role_id: 99994
    string: Earnest 'Earn' Marks

  - meta_key_id: 'credits:tv'
    media_entry_id: 11111
    person_id: 44442
    role_id: 99994
    string: Alfred 'Paper Boi' Miles
---
```
