### ISSUE TITLE
[filehandling] add explicit "profile" attribute to audio/video Previews

### ISSUE THREAD

**Issue by eins78** [Madek/madek#15]
for Previews with `media_type`: `audio` and `video`

---

currently:

```yaml
# config

zencoder_audio_output_formats_defaults:
 - {audio_codec: 'vorbis', skip_video: true}
 - {audio_codec: 'mp3', skip_video: true}

# DB
media_files:
  - id: mf1
previews:
  - id: p1, codec: mp3, media_file: mf1
  - id: p2, codec: vorbis, media_file: mf1
```

new:

```yaml
# config

zencoder_audio_output_formats:
 vorbis: {audio_codec: 'vorbis', skip_video: true}
 mp3: {audio_codec: 'mp3', skip_video: true}

# DB
media_files:
  - id: mf1
previews:
  - id: p1, conversion_profile: mp3, media_file: mf1
  - id: p2, conversion_profile: vorbis, media_file: mf1
```

There was already an attribute added which relates to the codec,
so to keep it simple we can rely on the following rules:
1. The _content_ of the existing configs won't change, just their structure (a map)
2. The key of each config in the map will be the same as the "codec"
(Because multiple configs with same config are not supported _yet_, we can safely assume this.)

---
questions:

Name of the attribute? `conversion_profile`? `preview_profile`? `madek_preview_profile`?
(Note that this is conceptually the same attribute as the `thumbnail` attr for Previews with media_type image, but we don't have to change that)

---

tasks

- [x] deploy: change config for audio, video (array to map)

- [x] DB: migration audio
  - [x] add `conversion_profile` attribute to `previews`
  - [x] set `conversion_profile` attribute for existing `previews`
         (find profile according to the "codec" prop, "id" of profile is the key of config in the map)
  - [x] remove persisted codec (we use profile instead)

- [x] DB: migration videos
  - [x] add `conversion_profile` attribute to `previews`
  - [x] set `conversion_profile` attribute for existing `previews`
         (find profile according to the "codec" prop, "id" of profile is the key of config in the map)

- [x] DB: migration zencoder_jobs ???

- [x] admin/webapp
  - [x] use new config name and format
  - [x] adjust the filtering etc in mediafiles controller
