### ISSUE TITLE
translations for platform texts (title, explore, etc)

### ISSUE THREAD

**Issue by eins78** [Madek/madek#180]
- [x] db, admin: strings @michalpodlecki 

- [x] UI/webapp @eins78 

current defaults as defined DB seeds (https://github.com/Madek/madek-datalayer/blob/f2e60fe1120802553523261a9fa4e7114bdd6ffa/db/seeds_and_defaults.yml#L225-L250). 

+ `support_url` by language

```yaml
MADEK_DEFAULT_SETTINGS:
  STRINGS:
    site_title: '** Name des Systems **'
    brand_text: '** Name des Anbieters **'
    brand_logo_url: null
    welcome_title: '** Wilkommen zum System **'
    welcome_text: '** Informationen zum System **'

    featured_set_title: '** Sehenswerte Inhalte **'
    featured_set_subtitle: '** Höhepunkte aus diesem Archiv. **'

    catalog_title: '** Katalog **'
    catalog_subtitle: '** Erkunden Sie den Katalog. **'

    media_entry_default_license_usage_meta_key: 'madek_core:copyright_notice'
    media_entry_default_license_usage_text: 'All Rights reserved.'

    about_page: |
      # About this Archive
      (Nothing here yet, configure content in [Admin Interface](/admin/app_settings))
    sitemap:
      - "About": "/about/"
      - "API": "/api/browser/"
      - "Software Madek": "https://zhdk.ch/madek"
      - "Madek Project on Github": "https://github.com/Madek"
```

example after translating:

```yaml
site_title: 
  de: '** Name des Systems **'
  en: '** Name of the System **'
```

changing the format/structure of the sitemap needs a bit more work, as the frontend (-templates) need to be adapted as well. It could look like this:

```yaml
sitemap:
  - url: "/about/"
    labels:
      de: "Über dieses Archiv"
      en: "About this Archive"
  - url: "/api/browser/"
    labels:
      de: "API Browser"
      en: "API Stöberer"
```
